### ISSUE TITLE
UI: Add threading to the UI elements

### ISSUE THREAD

**Issue by ong6** [AY2021S2-CS2103T-T12-4/tp#140]
To allow users to know their wait time. Users should not be able to type new commands while waiting for the previous one to finish.

**Comment by tlylt** [comment]
@tjtanjin FYI I will experiment with this for an hour or two now. If anything I will update this thread.

**Comment by tjtanjin** [comment]
![demo_threading](https://user-images.githubusercontent.com/43908963/110254519-7bad2c00-7fca-11eb-89b8-6648a27d20df.gif)

@tlylt I tinkered around with this as well. Unsure if there is any lag reduction but I imagine we can play around with the initial text to set in the box to mask this from the users. The counter is just a placeholder, I will likely replace it with `Processing Command...` (the dots will change between having 1 to 3 dots to reflect progress). Just 2 key points I wish to bring up:

- Firstly, although it works, the current code implementation feels rather messy because I had to wrap `Platform.runLater` a good 4-5 times around codes. If you had a better way to implement this, I'd love to hear it. If it helps, the reasoning behind my many uses of `Platform.runLater` is to deal with an error saying ` FX application thread; currentThread = Thread-4`
- Secondly, I did the UI threading within the `MainWindow#executeCommand` but this would mean that **sometimes**, even the fast commands like `add` and `remove` will see a quick flash of the counter (the pseudo progress indicator currently). Resolving this within `MainWindow` would look very messy as well. I am also still looking for a way to improve this.

I will tidy up and abstract parts of the code as much as I can tomorrow and try my best to make a PR before the team meeting so that we can further discuss this.
